source 'https://github.com/CocoaPods/Specs.git'

target 'MSRoutes_Example' do
  pod "MSRoutes", :path => "../"
end

target 'MSRoutes_Tests' do
  pod "MSRoutes", :path => "../"

#  pod 'Specta'
#  pod 'Expecta'
#  pod 'FBSnapshotTestCase'
#  pod 'Expecta+Snapshots'
end
